### ISSUE TITLE
data wanted

### ISSUE THREAD

**Issue by lifeforeal** [AICyberTeam/GABLE#3]
hi! great teachers 
i am a student from ningbo university. i am now working for my master degree paper which needs the dataset of Ningbo city. i will be really grateful if you can help me . and i will note and cite corretly with date using in my paper. if okay, please send dataset to my email 1173901145@qq.com  
                                                                                                                                                                                                sincerely yours
                                                                                                                                                                                                    Gimmy

**Comment by kwtk86** [comment]
浙江了已经发布了，链接已经挂出来了可以去下载
